import { $ } from 'bun'
import { writeFile } from 'fs/promises'
import { join } from 'path'

const API_KEY = 'ollama-123'

function generateNginxConfig() {
    return `# Nginx configuration for Ollama with API key authentication
# Generated by native_ollama setup script

events {
    worker_connections 1024;
}

http {
    # API key validation map
    map $http_x_api_key $api_key_valid {
        default 0;
        "${API_KEY}" 1;
    }

    # Upstream to Ollama service
    upstream ollama_backend {
        server 127.0.0.1:11434;
    }

    server {
        listen 80;
        server_name _;

        # Proxy /ollama requests to the ollama service
        location /ollama/ {
            # Check API key
            if ($api_key_valid = 0) {
                return 401 '{"error":"Unauthorized - Invalid or missing API key"}';
            }

            proxy_pass http://ollama_backend/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Increase timeouts for long-running LLM requests
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;

            # Disable buffering for streaming responses
            proxy_buffering off;
        }

        # Health check endpoint (no authentication required)
        location /health {
            access_log off;
            return 200 '{"status":"healthy"}';
            add_header Content-Type application/json;
        }

        # Return 404 for all other paths
        location / {
            return 404 '{"error":"Not found"}';
            add_header Content-Type application/json;
        }
    }
}
`
}

export async function configureNginxAuth() {
    console.log('\n🔐 Configuring Nginx with API key authentication...')
    console.log(`   API Key: ${API_KEY}`)

    try {
        // Generate nginx configuration
        console.log('📝 Generating Nginx configuration...')
        const nginxConfig = generateNginxConfig()

        // Write config to native_ollama directory
        const configPath = join(process.cwd(), 'native_ollama', 'nginx.conf')
        await writeFile(configPath, nginxConfig, 'utf-8')
        console.log(`✓ Nginx config written to: ${configPath}`)

        // Copy config to nginx directory
        console.log('📋 Deploying Nginx configuration...')
        await $`sudo cp ${configPath} /etc/nginx/nginx.conf`

        // Test nginx configuration
        console.log('🧪 Testing Nginx configuration...')
        await $`sudo nginx -t`
        console.log('✓ Nginx configuration is valid')

        // Reload nginx to apply changes
        console.log('🔄 Reloading Nginx...')
        await $`sudo systemctl reload nginx`
        console.log('✓ Nginx reloaded successfully')

    } catch (error) {
        console.log('✗ Failed to configure Nginx')
        console.log('\nError details:', error.message)
        throw new Error('Nginx configuration failed')
    }

    console.log('✓ Nginx configuration complete')
}
